### ISSUE TITLE
Thread issue

### ISSUE THREAD

**Issue by webispy** [nugu-developers/nugu-linux#174]
## Issue

The thread is stuck in `pthread_cond_wait()` state.

## Steps to Reproduce

1. Run sample application

```
nugusdk_start_sample ./examples/standalone/nugu_sample -d -m /var/lib/nugu/model
```

2. Select Listening

```
=======================================================
NUGU SDK Command (Connected)
=======================================================
w : start wakeup
l : start listening
s : stop listening
t : text input
m : set mic mute
c : connect
d : disconnect
q : quit
-------------------------------------------------------
Select Command > l
```

3. Select Quit during Listening mode

```
[ASR] LISTENING

=======================================================
NUGU SDK Command (Connected)
=======================================================
w : start wakeup
l : start listening
s : stop listening
t : text input
m : set mic mute
c : connect
d : disconnect
q : quit
-------------------------------------------------------
Select Command > q
```

### Threads

```
(gdb) info threads
  Id   Target Id         Frame
* 1    Thread 0x7f4312de27c0 (LWP 10558) "nugu_sample" 0x00007f431156c751 in NuguCore::AudioInputProcessor::~AudioInputProcessor (this=0x610000004a48, __in_chrg=<optimized out>)
    at /Volumes/work/git/github_my/nugu-linux/src/core/audio_input_processor.cc:43
  2    Thread 0x7f430b9fe700 (LWP 10571) "asr_loop" 0x00007f43104ec9f3 in pthread_cond_wait@@GLIBC_2.3.2 ()
   from /lib/x86_64-linux-gnu/libpthread.so.0
  3    Thread 0x7f430c1ff700 (LWP 10573) "http2" 0x00007f4310c2103f in select () from /lib/x86_64-linux-gnu/libc.so.6
```

### Thread-1 (mainloop) callstacks

```
#0  0x00007f43104e7d2d in __pthread_timedjoin_ex () at /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x00007f43111d08c3 in std::thread::join() () at /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#2  0x00007f431156c751 in NuguCore::AudioInputProcessor::~AudioInputProcessor() (this=0x610000004a48, __in_chrg=<optimized out>) at /Volumes/work/git/github_my/nugu-linux/src/core/audio_input_processor.cc:43
#3  0x00007f4311596c1b in NuguCore::SpeechRecognizer::~SpeechRecognizer() (this=0x610000004a40, __in_chrg=<optimized out>) at /Volumes/work/git/github_my/nugu-linux/src/core/speech_recognizer.hh:45
#4  0x00007f43115a28ad in NuguCapability::ASRAgent::~ASRAgent() (this=0x615000001480, __in_chrg=2, __vtt_parm=0x0)
    at /Volumes/work/git/github_my/nugu-linux/src/capability/asr_agent.cc:144
#5  0x00007f43115a2919 in NuguCapability::ASRAgent::~ASRAgent() (this=<optimized out>)
    at /Volumes/work/git/github_my/nugu-linux/src/capability/asr_agent.cc:146
#6  0x00007f43115a2949 in NuguCapability::ASRAgent::~ASRAgent() (this=0x615000001480)
    at /Volumes/work/git/github_my/nugu-linux/src/capability/asr_agent.cc:146
#7  0x0000560e94d88ef2 in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release() (this=0x603000021ee0)
    at /usr/include/c++/7/bits/shared_ptr_base.h:154
#8  0x0000560e94d88ef2 in std::__shared_count<(__gnu_cxx::_Lock_policy)2>::~__shared_count() (this=<optimized out>, __in_chrg=<optimized out>) at /usr/include/c++/7/bits/shared_ptr_base.h:684
#9  0x00007f4310b4d041 in  () at /lib/x86_64-linux-gnu/libc.so.6
#10 0x00007f4310b4d13a in  () at /lib/x86_64-linux-gnu/libc.so.6
#11 0x00007f4310b2bb9e in __libc_start_main () at /lib/x86_64-linux-gnu/libc.so.6
#12 0x0000560e94d839ea in _start ()
```

### Thread-2 (asr_loop) callstacks

```
#0  0x00007f43104ec9f3 in pthread_cond_wait@@GLIBC_2.3.2 () at /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x00007f431156a9b6 in nugu_recorder_get_frame_timeout (rec=0x60d000008c00, data=data@entry=0x7f430b9faab0 "\234", size=size@entry=0x7f430b9fdbb0, timeout=timeout@entry=0)
    at /Volumes/work/git/github_my/nugu-linux/src/base/nugu_recorder.c:404
#2  0x00007f43115735fd in NuguCore::AudioRecorderManager::getAudioFrame(NuguCore::IAudioRecorder*, char*, int*, int) (this=0x60e0000020a0, recorder=<optimized out>, data=<optimized out>, size=<optimized out>, timeout=0)
    at /Volumes/work/git/github_my/nugu-linux/src/core/audio_recorder_manager.cc:256
#3  0x00007f4311598e0c in NuguCore::SpeechRecognizer::loop() (this=0x610000004a40)
    at /Volumes/work/git/github_my/nugu-linux/src/core/speech_recognizer.cc:156
#4  0x00007f431156c46d in NuguCore::AudioInputProcessor::<lambda()>::operator() (__closure=<optimized out>)
    at /Volumes/work/git/github_my/nugu-linux/src/core/audio_input_processor.cc:62
#5  0x00007f431156c46d in std::__invoke_impl<void, NuguCore::AudioInputProcessor::init(std::__cxx11::string, std::__cxx11::string&, std::__cxx11::string&, std::__cxx11::string&)::<lambda()> > (__f=...)
    at /usr/include/c++/7/bits/invoke.h:60
#6  0x00007f431156c46d in std::__invoke<NuguCore::AudioInputProcessor::init(std::__cxx11::string, std::__cxx11::string&, std::__cxx11::string&, std::__cxx11::string&)::<lambda()> > (__fn=...) at /usr/include/c++/7/bits/invoke.h:95
#7  0x00007f431156c46d in std::thread::_Invoker<std::tuple<NuguCore::AudioInputProcessor::init(std::__cxx11::string, std::__cxx11::string&, std::__cxx11::string&, std::__cxx11::string&)::<lambda()> > >::_M_invoke<0> (this=<optimized out>)
    at /usr/include/c++/7/thread:234
#8  0x00007f431156c46d in std::thread::_Invoker<std::tuple<NuguCore::AudioInputProcessor::init(std::__cxx11::string, std::__cxx11::string&, std::__cxx11::string&, std::__cxx11::string&)::<lambda()> > >::operator() (this=<optimized out>)
    at /usr/include/c++/7/thread:243
#9  0x00007f431156c46d in std::thread::_State_impl<std::thread::_Invoker<std::tuple<NuguCore::AudioInputProcessor::init(std::__cxx11::string, std::__cxx11::string&, std::__cxx11::string&, std::__cxx11::string&)::<lambda()> > > >::_M_run(void) (this=<optimized out>) at /usr/include/c++/7/thread:186
#10 0x00007f43111d066f in  () at /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#11 0x00007f43104e66db in start_thread () at /lib/x86_64-linux-gnu/libpthread.so.0
#12 0x00007f4310c2b88f in clone () at /lib/x86_64-linux-gnu/libc.so.6
```

**Comment by JeanTracker** [comment]
Thanks. I'll check this issue.

**Comment by JeanTracker** [comment]
There is another issue and I created the new issue [#181](https://github.com/nugu-developers/nugu-linux/issues/181).
Please check it @webispy
