### ISSUE TITLE
Leak occurred in Directive Sequencer 

### ISSUE THREAD

**Issue by kimhyungrok** [nugu-developers/nugu-linux#175]
## Issue

When receiving directive which is not exist target CapabilityAgent in SDK, the directive sequencer's callback (CapabilityManager::dirseqCallback) return NUGU_DIRSEQ_REMOVE. In this situation, if you quit application, memory leak occurred.

## Steps to Reproduce

1. Remove DisplayAgent in nugu_sample

```
    // create capability instance
    nugu_client->getCapabilityBuilder()
        ->add(system_handler.get())
        ->add(asr_handler.get())
        ->add(tts_handler.get())
        ->add(audio_player_handler.get())
        ->add(text_handler.get())
        ->add(speaker_handler.get())
        ->add(mic_handler.get())
        // ->add(display_handler.get())
        ->construct();
```

2. Build NUGU SDK & Run sample application

```
=======================================================
NUGU SDK Command (Connected)
=======================================================
w : start wakeup
l : start listening
s : stop listening
t : text input
m : set mic mute
c : connect
d : disconnect
q : quit
-------------------------------------------------------
Select Command > 
```

3. Select Listening & Speak "된장찌게 레시피 알려줘"

```
=======================================================
NUGU SDK Command (Connected)
=======================================================
w : start wakeup
l : start listening
s : stop listening
t : text input
m : set mic mute
c : connect
d : disconnect
q : quit
-------------------------------------------------------
Select Command > l
[Display] requestLyricsPageAvailable
[ASR] LISTENING
[ASR] RECOGNIZING
[ASR] BUSY
[ASR] onComplete > 된장찌개 레시피 알려줘
[TTS] PLAYING..., dialog_id: 0855c4cdb701f9a949f020083eeb50f1
[ASR] IDLE
[Wakeup] wakeup detecting...
[TTS] TEXT > 구수하고 담백한, 된장찌개 레시피를 알려드릴게요. 들어가는 재료는, 2인분 기준으로, 새송이버섯 1개, 양파 반 개, 애호박 반 개, 청양고추 1개, 해감 된 바지락 1컵 이며, 선택 재료는, 홍고추 1개 입니다. 양념에는 된장, 쌈장이 들어갑니다. 재료를 모두 준비하셨다면, '{W}, 요리 시작'이라고 말씀해 주세요., dialog_id: 0855c4cdb701f9a949f020083eeb50f1
[Display] render display template - id: 158209950434196, type: AudioPlayer.Template1, dialog_id: 0855c4cdb701f9a949f020083eeb50f1
```

4. Select Quit

```
=======================================================
NUGU SDK Command (Connected)
=======================================================
w : start wakeup
l : start listening
s : stop listening
t : text input
m : set mic mute
c : connect
d : disconnect
q : quit
-------------------------------------------------------
Select Command > q
```

5. Leak Occurred

  - check below log

## Log

```
==4632==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 16384 byte(s) in 1 object(s) allocated from:
    #0 0x7f2c9c404602 in malloc (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x98602)
    #1 0x7f2c9c0aa7b8 in g_malloc (/lib/x86_64-linux-gnu/libglib-2.0.so.0+0x4f7b8)

Direct leak of 112 byte(s) in 1 object(s) allocated from:
    #0 0x7f2c9c40479a in __interceptor_calloc (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x9879a)
    #1 0x7f2c9bcea612 in nugu_directive_new /home/berserk/mac/mirror/nugu-linux/src/base/nugu_directive.c:64
    #2 0x7f2c9bcc460e in _body_json(char const*, unsigned long) [clone .isra.47] (/home/berserk/mac/mirror/nugu-linux/build/src/libnugu.so.0+0x8c60e)
    #3 0x7f2c9bcbe6d6 in multipart_parser_parse /home/berserk/mac/mirror/nugu-linux/src/base/network/http2/multipart_parser.c:311
    #4 0x7f2c9bcc2eac in _on_body /home/berserk/mac/mirror/nugu-linux/src/base/network/http2/v1_directives.cc:266
    #5 0x7f2c9bcbe8a9 in _response_body_cb /home/berserk/mac/mirror/nugu-linux/src/base/network/http2/http2_request.c:188
    #6 0x7f2c9bd7cf5c in chop_write /home/berserk/mac/mirror/nugu-linux/externals/curl/lib/sendf.c:600
    #7 0x7f2c9bd7d182 in Curl_client_write /home/berserk/mac/mirror/nugu-linux/externals/curl/lib/sendf.c:684
    #8 0x7f2c9bd88c03 in readwrite_data /home/berserk/mac/mirror/nugu-linux/externals/curl/lib/transfer.c:875
    #9 0x7f2c9bd89619 in Curl_readwrite /home/berserk/mac/mirror/nugu-linux/externals/curl/lib/transfer.c:1237
    #10 0x7f2c9bd4b70a in multi_runsingle /home/berserk/mac/mirror/nugu-linux/externals/curl/lib/multi.c:1963
    #11 0x7f2c9bd4beb0 in curl_multi_perform /home/berserk/mac/mirror/nugu-linux/externals/curl/lib/multi.c:2226
    #12 0x7f2c9bcc0499 in _loop /home/berserk/mac/mirror/nugu-linux/src/base/network/http2/http2_network.c:165
    #13 0x7f2c9b0c06b9 in start_thread (/lib/x86_64-linux-gnu/libpthread.so.0+0x76b9)

Indirect leak of 1265 byte(s) in 1 object(s) allocated from:
    #0 0x7f2c9c3ce30f in strdup (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x6230f)
    #1 0x7f2c9bcea6ff in nugu_directive_new /home/berserk/mac/mirror/nugu-linux/src/base/nugu_directive.c:71
    #2 0x7f2c9bcc460e in _body_json(char const*, unsigned long) [clone .isra.47] (/home/berserk/mac/mirror/nugu-linux/build/src/libnugu.so.0+0x8c60e)
    #3 0x7f2c9bcbe6d6 in multipart_parser_parse /home/berserk/mac/mirror/nugu-linux/src/base/network/http2/multipart_parser.c:311
    #4 0x7f2c9bcc2eac in _on_body /home/berserk/mac/mirror/nugu-linux/src/base/network/http2/v1_directives.cc:266
    #5 0x7f2c9bcbe8a9 in _response_body_cb /home/berserk/mac/mirror/nugu-linux/src/base/network/http2/http2_request.c:188
    #6 0x7f2c9bd7cf5c in chop_write /home/berserk/mac/mirror/nugu-linux/externals/curl/lib/sendf.c:600
    #7 0x7f2c9bd7d182 in Curl_client_write /home/berserk/mac/mirror/nugu-linux/externals/curl/lib/sendf.c:684
    #8 0x7f2c9bd88c03 in readwrite_data /home/berserk/mac/mirror/nugu-linux/externals/curl/lib/transfer.c:875
    #9 0x7f2c9bd89619 in Curl_readwrite /home/berserk/mac/mirror/nugu-linux/externals/curl/lib/transfer.c:1237
    #10 0x7f2c9bd4b70a in multi_runsingle /home/berserk/mac/mirror/nugu-linux/externals/curl/lib/multi.c:1963
    #11 0x7f2c9bd4beb0 in curl_multi_perform /home/berserk/mac/mirror/nugu-linux/externals/curl/lib/multi.c:2226
    #12 0x7f2c9bcc0499 in _loop /home/berserk/mac/mirror/nugu-linux/src/base/network/http2/http2_network.c:165
    #13 0x7f2c9b0c06b9 in start_thread (/lib/x86_64-linux-gnu/libpthread.so.0+0x76b9)

Indirect leak of 1024 byte(s) in 1 object(s) allocated from:
    #0 0x7f2c9c40479a in __interceptor_calloc (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x9879a)
    #1 0x7f2c9bce93a3 in nugu_buffer_new /home/berserk/mac/mirror/nugu-linux/src/base/nugu_buffer.c:51
    #2 0x7f2c9bcea76e in nugu_directive_new /home/berserk/mac/mirror/nugu-linux/src/base/nugu_directive.c:75
    #3 0x7f2c9bcc460e in _body_json(char const*, unsigned long) [clone .isra.47] (/home/berserk/mac/mirror/nugu-linux/build/src/libnugu.so.0+0x8c60e)
    #4 0x7f2c9bcbe6d6 in multipart_parser_parse /home/berserk/mac/mirror/nugu-linux/src/base/network/http2/multipart_parser.c:311
    #5 0x7f2c9bcc2eac in _on_body /home/berserk/mac/mirror/nugu-linux/src/base/network/http2/v1_directives.cc:266
    #6 0x7f2c9bcbe8a9 in _response_body_cb /home/berserk/mac/mirror/nugu-linux/src/base/network/http2/http2_request.c:188
    #7 0x7f2c9bd7cf5c in chop_write /home/berserk/mac/mirror/nugu-linux/externals/curl/lib/sendf.c:600
    #8 0x7f2c9bd7d182 in Curl_client_write /home/berserk/mac/mirror/nugu-linux/externals/curl/lib/sendf.c:684
    #9 0x7f2c9bd88c03 in readwrite_data /home/berserk/mac/mirror/nugu-linux/externals/curl/lib/transfer.c:875
    #10 0x7f2c9bd89619 in Curl_readwrite /home/berserk/mac/mirror/nugu-linux/externals/curl/lib/transfer.c:1237
    #11 0x7f2c9bd4b70a in multi_runsingle /home/berserk/mac/mirror/nugu-linux/externals/curl/lib/multi.c:1963
    #12 0x7f2c9bd4beb0 in curl_multi_perform /home/berserk/mac/mirror/nugu-linux/externals/curl/lib/multi.c:2226
    #13 0x7f2c9bcc0499 in _loop /home/berserk/mac/mirror/nugu-linux/src/base/network/http2/http2_network.c:165
    #14 0x7f2c9b0c06b9 in start_thread (/lib/x86_64-linux-gnu/libpthread.so.0+0x76b9)

Indirect leak of 72 byte(s) in 1 object(s) allocated from:
    #0 0x7f2c9c3ce30f in strdup (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x6230f)
    #1 0x7f2c9bcea725 in nugu_directive_new /home/berserk/mac/mirror/nugu-linux/src/base/nugu_directive.c:72
    #2 0x7f2c9bcc460e in _body_json(char const*, unsigned long) [clone .isra.47] (/home/berserk/mac/mirror/nugu-linux/build/src/libnugu.so.0+0x8c60e)
    #3 0x7f2c9bcbe6d6 in multipart_parser_parse /home/berserk/mac/mirror/nugu-linux/src/base/network/http2/multipart_parser.c:311
    #4 0x7f2c9bcc2eac in _on_body /home/berserk/mac/mirror/nugu-linux/src/base/network/http2/v1_directives.cc:266
    #5 0x7f2c9bcbe8a9 in _response_body_cb /home/berserk/mac/mirror/nugu-linux/src/base/network/http2/http2_request.c:188
    #6 0x7f2c9bd7cf5c in chop_write /home/berserk/mac/mirror/nugu-linux/externals/curl/lib/sendf.c:600
    #7 0x7f2c9bd7d182 in Curl_client_write /home/berserk/mac/mirror/nugu-linux/externals/curl/lib/sendf.c:684
    #8 0x7f2c9bd88c03 in readwrite_data /home/berserk/mac/mirror/nugu-linux/externals/curl/lib/transfer.c:875
    #9 0x7f2c9bd89619 in Curl_readwrite /home/berserk/mac/mirror/nugu-linux/externals/curl/lib/transfer.c:1237
    #10 0x7f2c9bd4b70a in multi_runsingle /home/berserk/mac/mirror/nugu-linux/externals/curl/lib/multi.c:1963
    #11 0x7f2c9bd4beb0 in curl_multi_perform /home/berserk/mac/mirror/nugu-linux/externals/curl/lib/multi.c:2226
    #12 0x7f2c9bcc0499 in _loop /home/berserk/mac/mirror/nugu-linux/src/base/network/http2/http2_network.c:165
    #13 0x7f2c9b0c06b9 in start_thread (/lib/x86_64-linux-gnu/libpthread.so.0+0x76b9)

Indirect leak of 33 byte(s) in 1 object(s) allocated from:
    #0 0x7f2c9c3ce30f in strdup (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x6230f)
    #1 0x7f2c9bcea68e in nugu_directive_new /home/berserk/mac/mirror/nugu-linux/src/base/nugu_directive.c:68
    #2 0x7f2c9bcc460e in _body_json(char const*, unsigned long) [clone .isra.47] (/home/berserk/mac/mirror/nugu-linux/build/src/libnugu.so.0+0x8c60e)
    #3 0x7f2c9bcbe6d6 in multipart_parser_parse /home/berserk/mac/mirror/nugu-linux/src/base/network/http2/multipart_parser.c:311
    #4 0x7f2c9bcc2eac in _on_body /home/berserk/mac/mirror/nugu-linux/src/base/network/http2/v1_directives.cc:266
    #5 0x7f2c9bcbe8a9 in _response_body_cb /home/berserk/mac/mirror/nugu-linux/src/base/network/http2/http2_request.c:188
    #6 0x7f2c9bd7cf5c in chop_write /home/berserk/mac/mirror/nugu-linux/externals/curl/lib/sendf.c:600
    #7 0x7f2c9bd7d182 in Curl_client_write /home/berserk/mac/mirror/nugu-linux/externals/curl/lib/sendf.c:684
    #8 0x7f2c9bd88c03 in readwrite_data /home/berserk/mac/mirror/nugu-linux/externals/curl/lib/transfer.c:875
    #9 0x7f2c9bd89619 in Curl_readwrite /home/berserk/mac/mirror/nugu-linux/externals/curl/lib/transfer.c:1237
    #10 0x7f2c9bd4b70a in multi_runsingle /home/berserk/mac/mirror/nugu-linux/externals/curl/lib/multi.c:1963
    #11 0x7f2c9bd4beb0 in curl_multi_perform /home/berserk/mac/mirror/nugu-linux/externals/curl/lib/multi.c:2226
    #12 0x7f2c9bcc0499 in _loop /home/berserk/mac/mirror/nugu-linux/src/base/network/http2/http2_network.c:165
    #13 0x7f2c9b0c06b9 in start_thread (/lib/x86_64-linux-gnu/libpthread.so.0+0x76b9)

Indirect leak of 33 byte(s) in 1 object(s) allocated from:
    #0 0x7f2c9c3ce30f in strdup (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x6230f)
    #1 0x7f2c9bcea6b3 in nugu_directive_new /home/berserk/mac/mirror/nugu-linux/src/base/nugu_directive.c:69
    #2 0x7f2c9bcc460e in _body_json(char const*, unsigned long) [clone .isra.47] (/home/berserk/mac/mirror/nugu-linux/build/src/libnugu.so.0+0x8c60e)
    #3 0x7f2c9bcbe6d6 in multipart_parser_parse /home/berserk/mac/mirror/nugu-linux/src/base/network/http2/multipart_parser.c:311
    #4 0x7f2c9bcc2eac in _on_body /home/berserk/mac/mirror/nugu-linux/src/base/network/http2/v1_directives.cc:266
    #5 0x7f2c9bcbe8a9 in _response_body_cb /home/berserk/mac/mirror/nugu-linux/src/base/network/http2/http2_request.c:188
    #6 0x7f2c9bd7cf5c in chop_write /home/berserk/mac/mirror/nugu-linux/externals/curl/lib/sendf.c:600
    #7 0x7f2c9bd7d182 in Curl_client_write /home/berserk/mac/mirror/nugu-linux/externals/curl/lib/sendf.c:684
    #8 0x7f2c9bd88c03 in readwrite_data /home/berserk/mac/mirror/nugu-linux/externals/curl/lib/transfer.c:875
    #9 0x7f2c9bd89619 in Curl_readwrite /home/berserk/mac/mirror/nugu-linux/externals/curl/lib/transfer.c:1237
    #10 0x7f2c9bd4b70a in multi_runsingle /home/berserk/mac/mirror/nugu-linux/externals/curl/lib/multi.c:1963
    #11 0x7f2c9bd4beb0 in curl_multi_perform /home/berserk/mac/mirror/nugu-linux/externals/curl/lib/multi.c:2226
    #12 0x7f2c9bcc0499 in _loop /home/berserk/mac/mirror/nugu-linux/src/base/network/http2/http2_network.c:165
    #13 0x7f2c9b0c06b9 in start_thread (/lib/x86_64-linux-gnu/libpthread.so.0+0x76b9)

Indirect leak of 24 byte(s) in 1 object(s) allocated from:
    #0 0x7f2c9c40479a in __interceptor_calloc (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x9879a)
    #1 0x7f2c9bce930a in nugu_buffer_new /home/berserk/mac/mirror/nugu-linux/src/base/nugu_buffer.c:39
    #2 0x7f2c9bcea76e in nugu_directive_new /home/berserk/mac/mirror/nugu-linux/src/base/nugu_directive.c:75
    #3 0x7f2c9bcc460e in _body_json(char const*, unsigned long) [clone .isra.47] (/home/berserk/mac/mirror/nugu-linux/build/src/libnugu.so.0+0x8c60e)
    #4 0x7f2c9bcbe6d6 in multipart_parser_parse /home/berserk/mac/mirror/nugu-linux/src/base/network/http2/multipart_parser.c:311
    #5 0x7f2c9bcc2eac in _on_body /home/berserk/mac/mirror/nugu-linux/src/base/network/http2/v1_directives.cc:266
    #6 0x7f2c9bcbe8a9 in _response_body_cb /home/berserk/mac/mirror/nugu-linux/src/base/network/http2/http2_request.c:188
    #7 0x7f2c9bd7cf5c in chop_write /home/berserk/mac/mirror/nugu-linux/externals/curl/lib/sendf.c:600
    #8 0x7f2c9bd7d182 in Curl_client_write /home/berserk/mac/mirror/nugu-linux/externals/curl/lib/sendf.c:684
    #9 0x7f2c9bd88c03 in readwrite_data /home/berserk/mac/mirror/nugu-linux/externals/curl/lib/transfer.c:875
    #10 0x7f2c9bd89619 in Curl_readwrite /home/berserk/mac/mirror/nugu-linux/externals/curl/lib/transfer.c:1237
    #11 0x7f2c9bd4b70a in multi_runsingle /home/berserk/mac/mirror/nugu-linux/externals/curl/lib/multi.c:1963
    #12 0x7f2c9bd4beb0 in curl_multi_perform /home/berserk/mac/mirror/nugu-linux/externals/curl/lib/multi.c:2226
    #13 0x7f2c9bcc0499 in _loop /home/berserk/mac/mirror/nugu-linux/src/base/network/http2/http2_network.c:165
    #14 0x7f2c9b0c06b9 in start_thread (/lib/x86_64-linux-gnu/libpthread.so.0+0x76b9)

Indirect leak of 11 byte(s) in 1 object(s) allocated from:
    #0 0x7f2c9c3ce30f in strdup (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x6230f)
    #1 0x7f2c9bcea644 in nugu_directive_new /home/berserk/mac/mirror/nugu-linux/src/base/nugu_directive.c:66
    #2 0x7f2c9bcc460e in _body_json(char const*, unsigned long) [clone .isra.47] (/home/berserk/mac/mirror/nugu-linux/build/src/libnugu.so.0+0x8c60e)
    #3 0x7f2c9bcbe6d6 in multipart_parser_parse /home/berserk/mac/mirror/nugu-linux/src/base/network/http2/multipart_parser.c:311
    #4 0x7f2c9bcc2eac in _on_body /home/berserk/mac/mirror/nugu-linux/src/base/network/http2/v1_directives.cc:266
    #5 0x7f2c9bcbe8a9 in _response_body_cb /home/berserk/mac/mirror/nugu-linux/src/base/network/http2/http2_request.c:188
    #6 0x7f2c9bd7cf5c in chop_write /home/berserk/mac/mirror/nugu-linux/externals/curl/lib/sendf.c:600
    #7 0x7f2c9bd7d182 in Curl_client_write /home/berserk/mac/mirror/nugu-linux/externals/curl/lib/sendf.c:684
    #8 0x7f2c9bd88c03 in readwrite_data /home/berserk/mac/mirror/nugu-linux/externals/curl/lib/transfer.c:875
    #9 0x7f2c9bd89619 in Curl_readwrite /home/berserk/mac/mirror/nugu-linux/externals/curl/lib/transfer.c:1237
    #10 0x7f2c9bd4b70a in multi_runsingle /home/berserk/mac/mirror/nugu-linux/externals/curl/lib/multi.c:1963
    #11 0x7f2c9bd4beb0 in curl_multi_perform /home/berserk/mac/mirror/nugu-linux/externals/curl/lib/multi.c:2226
    #12 0x7f2c9bcc0499 in _loop /home/berserk/mac/mirror/nugu-linux/src/base/network/http2/http2_network.c:165
    #13 0x7f2c9b0c06b9 in start_thread (/lib/x86_64-linux-gnu/libpthread.so.0+0x76b9)

Indirect leak of 8 byte(s) in 1 object(s) allocated from:
    #0 0x7f2c9c3ce30f in strdup (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x6230f)
    #1 0x7f2c9bcea621 in nugu_directive_new /home/berserk/mac/mirror/nugu-linux/src/base/nugu_directive.c:65
    #2 0x7f2c9bcc460e in _body_json(char const*, unsigned long) [clone .isra.47] (/home/berserk/mac/mirror/nugu-linux/build/src/libnugu.so.0+0x8c60e)
    #3 0x7f2c9bcbe6d6 in multipart_parser_parse /home/berserk/mac/mirror/nugu-linux/src/base/network/http2/multipart_parser.c:311
    #4 0x7f2c9bcc2eac in _on_body /home/berserk/mac/mirror/nugu-linux/src/base/network/http2/v1_directives.cc:266
    #5 0x7f2c9bcbe8a9 in _response_body_cb /home/berserk/mac/mirror/nugu-linux/src/base/network/http2/http2_request.c:188
    #6 0x7f2c9bd7cf5c in chop_write /home/berserk/mac/mirror/nugu-linux/externals/curl/lib/sendf.c:600
    #7 0x7f2c9bd7d182 in Curl_client_write /home/berserk/mac/mirror/nugu-linux/externals/curl/lib/sendf.c:684
    #8 0x7f2c9bd88c03 in readwrite_data /home/berserk/mac/mirror/nugu-linux/externals/curl/lib/transfer.c:875
    #9 0x7f2c9bd89619 in Curl_readwrite /home/berserk/mac/mirror/nugu-linux/externals/curl/lib/transfer.c:1237
    #10 0x7f2c9bd4b70a in multi_runsingle /home/berserk/mac/mirror/nugu-linux/externals/curl/lib/multi.c:1963
    #11 0x7f2c9bd4beb0 in curl_multi_perform /home/berserk/mac/mirror/nugu-linux/externals/curl/lib/multi.c:2226
    #12 0x7f2c9bcc0499 in _loop /home/berserk/mac/mirror/nugu-linux/src/base/network/http2/http2_network.c:165
    #13 0x7f2c9b0c06b9 in start_thread (/lib/x86_64-linux-gnu/libpthread.so.0+0x76b9)

Indirect leak of 4 byte(s) in 1 object(s) allocated from:
    #0 0x7f2c9c3ce30f in strdup (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x6230f)
    #1 0x7f2c9bcea669 in nugu_directive_new /home/berserk/mac/mirror/nugu-linux/src/base/nugu_directive.c:67
    #2 0x7f2c9bcc460e in _body_json(char const*, unsigned long) [clone .isra.47] (/home/berserk/mac/mirror/nugu-linux/build/src/libnugu.so.0+0x8c60e)
    #3 0x7f2c9bcbe6d6 in multipart_parser_parse /home/berserk/mac/mirror/nugu-linux/src/base/network/http2/multipart_parser.c:311
    #4 0x7f2c9bcc2eac in _on_body /home/berserk/mac/mirror/nugu-linux/src/base/network/http2/v1_directives.cc:266
    #5 0x7f2c9bcbe8a9 in _response_body_cb /home/berserk/mac/mirror/nugu-linux/src/base/network/http2/http2_request.c:188
    #6 0x7f2c9bd7cf5c in chop_write /home/berserk/mac/mirror/nugu-linux/externals/curl/lib/sendf.c:600
    #7 0x7f2c9bd7d182 in Curl_client_write /home/berserk/mac/mirror/nugu-linux/externals/curl/lib/sendf.c:684
    #8 0x7f2c9bd88c03 in readwrite_data /home/berserk/mac/mirror/nugu-linux/externals/curl/lib/transfer.c:875
    #9 0x7f2c9bd89619 in Curl_readwrite /home/berserk/mac/mirror/nugu-linux/externals/curl/lib/transfer.c:1237
    #10 0x7f2c9bd4b70a in multi_runsingle /home/berserk/mac/mirror/nugu-linux/externals/curl/lib/multi.c:1963
    #11 0x7f2c9bd4beb0 in curl_multi_perform /home/berserk/mac/mirror/nugu-linux/externals/curl/lib/multi.c:2226
    #12 0x7f2c9bcc0499 in _loop /home/berserk/mac/mirror/nugu-linux/src/base/network/http2/http2_network.c:165
    #13 0x7f2c9b0c06b9 in start_thread (/lib/x86_64-linux-gnu/libpthread.so.0+0x76b9)

Indirect leak of 1 byte(s) in 1 object(s) allocated from:
    #0 0x7f2c9c3ce30f in strdup (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x6230f)
    #1 0x7f2c9bcea6d9 in nugu_directive_new /home/berserk/mac/mirror/nugu-linux/src/base/nugu_directive.c:70
    #2 0x7f2c9bcc460e in _body_json(char const*, unsigned long) [clone .isra.47] (/home/berserk/mac/mirror/nugu-linux/build/src/libnugu.so.0+0x8c60e)
    #3 0x7f2c9bcbe6d6 in multipart_parser_parse /home/berserk/mac/mirror/nugu-linux/src/base/network/http2/multipart_parser.c:311
    #4 0x7f2c9bcc2eac in _on_body /home/berserk/mac/mirror/nugu-linux/src/base/network/http2/v1_directives.cc:266
    #5 0x7f2c9bcbe8a9 in _response_body_cb /home/berserk/mac/mirror/nugu-linux/src/base/network/http2/http2_request.c:188
    #6 0x7f2c9bd7cf5c in chop_write /home/berserk/mac/mirror/nugu-linux/externals/curl/lib/sendf.c:600
    #7 0x7f2c9bd7d182 in Curl_client_write /home/berserk/mac/mirror/nugu-linux/externals/curl/lib/sendf.c:684
    #8 0x7f2c9bd88c03 in readwrite_data /home/berserk/mac/mirror/nugu-linux/externals/curl/lib/transfer.c:875
    #9 0x7f2c9bd89619 in Curl_readwrite /home/berserk/mac/mirror/nugu-linux/externals/curl/lib/transfer.c:1237
    #10 0x7f2c9bd4b70a in multi_runsingle /home/berserk/mac/mirror/nugu-linux/externals/curl/lib/multi.c:1963
    #11 0x7f2c9bd4beb0 in curl_multi_perform /home/berserk/mac/mirror/nugu-linux/externals/curl/lib/multi.c:2226
    #12 0x7f2c9bcc0499 in _loop /home/berserk/mac/mirror/nugu-linux/src/base/network/http2/http2_network.c:165
    #13 0x7f2c9b0c06b9 in start_thread (/lib/x86_64-linux-gnu/libpthread.so.0+0x76b9)
```

**Comment by webispy** [comment]
Thank you !

**Comment by webispy** [comment]
@kimhyungrok  Please re-test with latest commit and let me know the result. Thank you.

**Comment by kimhyungrok** [comment]
I checked that no leak occurred in same situation, so, I guess it seems fixed. Thank you!
